# Generated by Django 4.2.4 on 2023-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veggies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=150)),
                ('receipe_description', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
